# Generated by Django 3.0.3 on 2020-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='notes',
            field=models.TextField(default='The Case notes', help_text='Notes om the Case involving the Parties'),
        ),
    ]
